{% set version = "2.1.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-boolnet
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/BoolNet_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/BoolNet/BoolNet_{{ version }}.tar.gz
  sha256: 13579536a816cf0fa424916dfa1f868309421f8a3ed389d3fa63ba9d06d3de85

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-xml
    - r-igraph >=0.6
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-xml
    - r-igraph >=0.6

test:
  commands:
    - $R -e "library('BoolNet')"           # [not win]
    - "\"%R%\" -e \"library('BoolNet')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=BoolNet
  license: Artistic-2.0
  summary: Provides methods to reconstruct and generate synchronous, asynchronous, probabilistic
    and temporal Boolean networks, and to analyze and visualize attractors in Boolean
    networks.
  license_family: OTHER
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/Artistic-2.0'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
    - dpryan79
